virhi_rest_api_doctrine_api:
    path:     /api/doctrine
    defaults: { _controller: VirhiRestApiDoctrineBundle:Api:api }

virhi_rest_api_doctrine_entit_info:
    path:     /api/info
    defaults: { _controller: VirhiRestApiDoctrineBundle:Api:entitInfo }

virhi_rest_api_doctrine_list_object:
    path:     /api/objects
    defaults: { _controller: VirhiRestApiDoctrineBundle:Object:listObject }

virhi_rest_api_doctrine_object:
    path:     /api/object/{name}
    defaults: { _controller: VirhiRestApiDoctrineBundle:Object:object }

virhi_rest_api_doctrine_list_entity:
    path:     /api/entitys/{name}/{limit}
    defaults: { _controller: VirhiRestApiDoctrineBundle:Entity:listEntity, limit: null  }

virhi_rest_api_doctrine_entity:
    path:     /api/entity/{name}/{id}
    defaults: { _controller: VirhiRestApiDoctrineBundle:Entity:entity }

virhi_rest_api_doctrine_entity_create:
    methods:
        - POST
        - PUT
    path:     /api/create/{name}
    defaults: { _controller: VirhiRestApiDoctrineBundle:WriteEntity:create }

virhi_rest_api_doctrine_entity_update:
    methods:
        - POST
        - PUT
    path:     /api/update/{name}/{id}
    defaults: { _controller: VirhiRestApiDoctrineBundle:WriteEntity:update }

virhi_rest_api_doctrine_entity_remove:
    methods:
        - DELETE
    path:     /api/remove/{name}/{id}
    defaults: { _controller: VirhiRestApiDoctrineBundle:WriteEntity:remove }
