parameters:
    virhi_rest_api_doctrine.transformer.contexttosearch.entity.entity.class: Virhi\LazyRestApiBundle\Api\Transformer\ContextToSearch\Entity\EntityTransformer
    virhi_rest_api_doctrine.transformer.contexttosearch.entity.remove.class: Virhi\LazyRestApiBundle\Api\Transformer\ContextToSearch\Entity\RemoveEntityTransformer
    virhi_rest_api_doctrine.transformer.contexttosearch.entity.list_entity.class: Virhi\LazyRestApiBundle\Api\Transformer\ContextToSearch\Entity\ListEntityTransformer

    virhi_rest_api_doctrine.transformer.contexttosearch.object.list_object.class: Virhi\LazyRestApiBundle\Api\Transformer\ContextToSearch\Object\ListObjectTransformer
    virhi_rest_api_doctrine.transformer.contexttosearch.object.object.class: Virhi\LazyRestApiBundle\Api\Transformer\ContextToSearch\Object\ObjectTransformer

    virhi_rest_api_doctrine.transformer.entity.entity.class: Virhi\LazyRestApiBundle\Api\Transformer\Entity\EntityTransformer
    virhi_rest_api_doctrine.transformer.entity.list_entity.class: Virhi\LazyRestApiBundle\Api\Transformer\Entity\ListEntityTransformer

    virhi_rest_api_doctrine.transformer.form_data_to_entity.entity.class: Virhi\LazyRestApiBundle\Api\Transformer\FormDataToEntity\EntityTransformer

services:

    virhi_rest_api_doctrine.transformer.contexttosearch.entity.entity:
        class: %virhi_rest_api_doctrine.transformer.contexttosearch.entity.entity.class%

    virhi_rest_api_doctrine.transformer.contexttosearch.entity.remove:
        class: %virhi_rest_api_doctrine.transformer.contexttosearch.entity.remove.class%

    virhi_rest_api_doctrine.transformer.contexttosearch.entity.list_entity:
        class: %virhi_rest_api_doctrine.transformer.contexttosearch.entity.list_entity.class%

    virhi_rest_api_doctrine.transformer.contexttosearch.object.list_object:
        class: %virhi_rest_api_doctrine.transformer.contexttosearch.object.list_object.class%

    virhi_rest_api_doctrine.transformer.contexttosearch.object.object:
        class: %virhi_rest_api_doctrine.transformer.contexttosearch.object.object.class%
        arguments:
            - @virhi_rest_api_doctrine.service.entity_namespace

    virhi_rest_api_doctrine.transformer.entity.entity:
        class: %virhi_rest_api_doctrine.transformer.entity.entity.class%
        arguments:
            - @doctrine

    virhi_rest_api_doctrine.transformer.entity.list_entity:
        class: %virhi_rest_api_doctrine.transformer.entity.list_entity.class%
        arguments:
            - @doctrine

    virhi_rest_api_doctrine.transformer.form_data_to_entity.entity:
        class: %virhi_rest_api_doctrine.transformer.form_data_to_entity.entity.class%
        arguments:
            - @virhi_rest_api_doctrine.service.entity_namespace
            - @virhi_rest_api_doctrine.service.object
            - @virhi_rest_api_doctrine.service.entity