imports:
    - { resource: repositories.yml }
    - { resource: queries.yml }

parameters:
#    virhi_rest_api_doctrine.example.class: Virhi\RestApiDoctrineBundle\Example

services:
#    virhi_rest_api_doctrine.example:
#        class: %virhi_rest_api_doctrine.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
