imports:
    - { resource: repositories.yml }
    - { resource: queries.yml }
    - { resource: commands.yml }

parameters:
    virhi_rest_api_doctrine.service.entity_namespace.class: Virhi\RestApiDoctrineBundle\Api\Service\EntityNamespaceService
    virhi_rest_api_doctrine.service.object.class: Virhi\RestApiDoctrineBundle\Api\Service\ObjectService

services:
    virhi_rest_api_doctrine.service.entity_namespace:
        class: %virhi_rest_api_doctrine.service.entity_namespace.class%
        arguments: [@doctrine]

    virhi_rest_api_doctrine.service.object:
        class: %virhi_rest_api_doctrine.service.object.class%
        arguments: [@virhi_rest_api_doctrine.repository.object.finder]
